/**
 * Flowtype definitions for cancellation
 * Generated by Flowgen from a Typescript Definition
 * Flowgen v1.2.0
 * Author: [Joar Wilk](http://twitter.com/joarwilk)
 * Repo: http://github.com/joarwilk/flowgen
 */

/**
 * Defines a CancellationToken. This interface is not
 * intended to be implemented. A CancellationToken must
be created via a CancellationTokenSource.
*/
declare module 'vscode-jsonrpc/lib/cancellation' {
  declare export interface ICancellationToken {
    /**
     * Is `true` when the token has been cancelled, `false` otherwise.
     */
    isCancellationRequested: boolean;

    /**
     * An [event](#Event) which fires upon cancellation.
     */
    onCancellationRequested: Event<any>;
  }

  declare export var CancellationToken: {
    None: ICancellationToken,
    Cancelled: ICancellationToken,
    is(value: any): ICancellationToken,
  };

  declare export class CancellationTokenSource {
    token: CancellationToken;
    cancel(): void;
    dispose(): void;
  }
}
