// flow-typed signature: a8ccb619e3aba6efd814483c50d5d2aa
// flow-typed version: <<STUB>>/log4js_v3.0.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'log4js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'log4js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'log4js/lib/appenders/adapters' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/categoryFilter' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/console' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/dateFile' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/file' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/fileSync' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/index' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/logLevelFilter' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/multiFile' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/multiprocess' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/recording' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/stderr' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/stdout' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/tcp-server' {
  declare module.exports: any;
}

declare module 'log4js/lib/appenders/tcp' {
  declare module.exports: any;
}

declare module 'log4js/lib/categories' {
  declare module.exports: any;
}

declare module 'log4js/lib/clustering' {
  declare module.exports: any;
}

declare module 'log4js/lib/configuration' {
  declare module.exports: any;
}

declare module 'log4js/lib/connect-logger' {
  declare module.exports: any;
}

declare module 'log4js/lib/layouts' {
  declare module.exports: any;
}

declare module 'log4js/lib/levels' {
  declare module.exports: any;
}

declare module 'log4js/lib/log4js' {
  declare module.exports: any;
}

declare module 'log4js/lib/logger' {
  declare module.exports: any;
}

declare module 'log4js/lib/LoggingEvent' {
  declare module.exports: any;
}

// Filename aliases
declare module 'log4js/lib/appenders/adapters.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/adapters'>;
}
declare module 'log4js/lib/appenders/categoryFilter.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/categoryFilter'>;
}
declare module 'log4js/lib/appenders/console.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/console'>;
}
declare module 'log4js/lib/appenders/dateFile.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/dateFile'>;
}
declare module 'log4js/lib/appenders/file.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/file'>;
}
declare module 'log4js/lib/appenders/fileSync.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/fileSync'>;
}
declare module 'log4js/lib/appenders/index.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/index'>;
}
declare module 'log4js/lib/appenders/logLevelFilter.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/logLevelFilter'>;
}
declare module 'log4js/lib/appenders/multiFile.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/multiFile'>;
}
declare module 'log4js/lib/appenders/multiprocess.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/multiprocess'>;
}
declare module 'log4js/lib/appenders/recording.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/recording'>;
}
declare module 'log4js/lib/appenders/stderr.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/stderr'>;
}
declare module 'log4js/lib/appenders/stdout.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/stdout'>;
}
declare module 'log4js/lib/appenders/tcp-server.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/tcp-server'>;
}
declare module 'log4js/lib/appenders/tcp.js' {
  declare module.exports: $Exports<'log4js/lib/appenders/tcp'>;
}
declare module 'log4js/lib/categories.js' {
  declare module.exports: $Exports<'log4js/lib/categories'>;
}
declare module 'log4js/lib/clustering.js' {
  declare module.exports: $Exports<'log4js/lib/clustering'>;
}
declare module 'log4js/lib/configuration.js' {
  declare module.exports: $Exports<'log4js/lib/configuration'>;
}
declare module 'log4js/lib/connect-logger.js' {
  declare module.exports: $Exports<'log4js/lib/connect-logger'>;
}
declare module 'log4js/lib/layouts.js' {
  declare module.exports: $Exports<'log4js/lib/layouts'>;
}
declare module 'log4js/lib/levels.js' {
  declare module.exports: $Exports<'log4js/lib/levels'>;
}
declare module 'log4js/lib/log4js.js' {
  declare module.exports: $Exports<'log4js/lib/log4js'>;
}
declare module 'log4js/lib/logger.js' {
  declare module.exports: $Exports<'log4js/lib/logger'>;
}
declare module 'log4js/lib/LoggingEvent.js' {
  declare module.exports: $Exports<'log4js/lib/LoggingEvent'>;
}
