// flow-typed signature: c462d710bd9caf54671a6086b1f2f51b
// flow-typed version: <<STUB>>/vscode-uri_v1.0.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vscode-uri'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vscode-uri' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vscode-uri/lib/esm/index' {
  declare module.exports: any;
}

declare module 'vscode-uri/lib/umd/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vscode-uri/lib/esm/index.js' {
  declare module.exports: $Exports<'vscode-uri/lib/esm/index'>;
}
declare module 'vscode-uri/lib/umd/index.js' {
  declare module.exports: $Exports<'vscode-uri/lib/umd/index'>;
}
